// Generated by test/ts/pbt/emitQueueReplayFixture.ts - do not edit by hand.
// Regenerate: npm run generate:oracle-fixture

module {
  public type Op = {
    #pushFront : Nat;
    #pushBack : Nat;
    #popFront;
    #popBack;
  };

  public let trace : [Op] = [ #pushBack(10), #pushFront(5), #pushBack(7), #popFront, #popBack, #pushFront(1), #popFront ];

  public let expectedFinal : [Nat] = [ 10 ];
};
