import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import fc from "fast-check";
import type { OracleOp } from "./oracleOps";
import { applyOracleOps } from "./oracleOps";
import {
  commandToOracleOp,
  queueCommandArbitrary,
  type QueueModel,
} from "./pureQueueCommands";
import { OracleDeque } from "./references/arrayDequeOracle";

const __dirname = dirname(fileURLToPath(import.meta.url));

/** Number of replay scenarios emitted for Motoko tests. */
export const FIXTURE_COUNT = 100;

function maxCommandsForFixture(index: number): number {
  return 1 + ((index * 17 + index * index * 5) % 500);
}

function seedForFixture(index: number, baseSeed: number): number {
  return (baseSeed + index * 100_003) >>> 0;
}

/**
 * Same selection as `fc.modelRun`: skip commands whose `check` fails on the
 * current model (fast-check still includes those in the iterable).
 */
function sampleOps(maxCommands: number, seed: number): OracleOp[] {
  const samples = fc.sample(
    queueCommandArbitrary({ maxCommands }),
    { seed, numRuns: 1 },
  );
  const iterable = samples[0] as Iterable<
    fc.Command<QueueModel, OracleDeque>
  >;
  const model: QueueModel = { items: [] };
  const real = new OracleDeque();
  const ops: OracleOp[] = [];
  for (const cmd of iterable) {
    if (!cmd.check(model)) {
      continue;
    }
    ops.push(commandToOracleOp(cmd));
    cmd.run(model, real);
  }
  return ops;
}

function motokoNatArray(values: readonly number[]): string {
  if (values.length === 0) {
    return "[]";
  }
  return "[ " + values.map((n) => String(n)).join(", ") + " ]";
}

function motokoOpArray(ops: readonly OracleOp[]): string {
  if (ops.length === 0) {
    return "[]";
  }
  const parts: string[] = [];
  for (const op of ops) {
    switch (op.kind) {
      case "pushFront":
        parts.push(`#pushFront(${op.value})`);
        break;
      case "pushBack":
        parts.push(`#pushBack(${op.value})`);
        break;
      case "popFront":
        parts.push("#popFront");
        break;
      case "popBack":
        parts.push("#popBack");
        break;
    }
  }
  return "[ " + parts.join(", ") + " ]";
}

function buildModule(baseSeed: number): string {
  const fixtureLiterals: string[] = [];
  for (let i = 0; i < FIXTURE_COUNT; i++) {
    const maxCommands = maxCommandsForFixture(i);
    const seed = seedForFixture(i, baseSeed);
    const ops = sampleOps(maxCommands, seed);
    const expected = applyOracleOps(ops);
    fixtureLiterals.push(
      `{ trace = ${motokoOpArray(ops)}; expectedFinal = ${motokoNatArray(expected)} }`,
    );
  }

  return `// Generated by test/ts/pbt/emitOracleFixtures.ts - do not edit by hand.
// Regenerate: npm run generate:oracle-fixtures
// Reproduce this file: ORACLE_FIXTURE_SEED=${baseSeed} npm run generate:oracle-fixtures

module {
  public type Op = {
    #pushFront : Nat;
    #pushBack : Nat;
    #popFront;
    #popBack;
  };

  public type Fixture = {
    trace : [Op];
    expectedFinal : [Nat];
  };

  public let fixtureCount : Nat = ${FIXTURE_COUNT};

  public let fixtures : [Fixture] = [ ${fixtureLiterals.join(", ")} ];
};
`;
}

export function writeQueueOracleFixtures(baseSeed: number): void {
  const outDir = join(__dirname, "../../generated");
  mkdirSync(outDir, { recursive: true });
  const outPath = join(outDir, "QueueOracleFixtures.mo");
  writeFileSync(outPath, buildModule(baseSeed), "utf8");
  console.log(`Wrote ${outPath} (${FIXTURE_COUNT} fixtures, base seed ${baseSeed})`);
}
