import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { TRACE, expectedFinalFromTrace } from "./fixtures/queueOracleTrace";

const __dirname = dirname(fileURLToPath(import.meta.url));

function motokoNatArray(values: readonly number[]): string {
  if (values.length === 0) {
    return "[]";
  }
  return "[ " + values.map((n) => String(n)).join(", ") + " ]";
}

function motokoOpArray(): string {
  const parts: string[] = [];
  for (const op of TRACE) {
    switch (op.kind) {
      case "pushFront":
        parts.push(`#pushFront(${op.value})`);
        break;
      case "pushBack":
        parts.push(`#pushBack(${op.value})`);
        break;
      case "popFront":
        parts.push("#popFront");
        break;
      case "popBack":
        parts.push("#popBack");
        break;
    }
  }
  return "[ " + parts.join(", ") + " ]";
}

function emit(): string {
  const expected = expectedFinalFromTrace();
  return `// Generated by test/ts/pbt/emitQueueReplayFixture.ts - do not edit by hand.
// Regenerate: npm run generate:oracle-fixture

module {
  public type Op = {
    #pushFront : Nat;
    #pushBack : Nat;
    #popFront;
    #popBack;
  };

  public let trace : [Op] = ${motokoOpArray()};

  public let expectedFinal : [Nat] = ${motokoNatArray(expected)};
};
`;
}

const outDir = join(__dirname, "../../oracleReplay");
mkdirSync(outDir, { recursive: true });
const outPath = join(outDir, "QueueReplayFixture.mo");
writeFileSync(outPath, emit(), "utf8");
console.log(`Wrote ${outPath}`);
