import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import fc from "fast-check";
import type { MapMutationOp } from "./mapOracleOps";
import { applyMapMutationOps } from "./mapOracleOps";
import {
  commandToMapMutationOp,
  mapCommandArbitrary,
  type MapModel,
} from "./pureMapCommands";
import { OracleNatTextMap } from "./references/oracleNatTextMap";

const __dirname = dirname(fileURLToPath(import.meta.url));

export const FIXTURE_COUNT = 100;

function maxCommandsForFixture(index: number): number {
  return 1 + ((index * 19 + index * index * 7) % 500);
}

function seedForFixture(index: number, baseSeed: number): number {
  return (baseSeed + index * 97_981) >>> 0;
}

function motokoTextLiteral(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`;
}

function motokoMutationOpsArray(ops: readonly MapMutationOp[]): string {
  if (ops.length === 0) {
    return "[]";
  }
  const parts: string[] = [];
  for (const op of ops) {
    switch (op.kind) {
      case "add":
        parts.push(`#add(${op.key}, ${motokoTextLiteral(op.value)})`);
        break;
      case "remove":
        parts.push(`#remove(${op.key})`);
        break;
    }
  }
  return "[ " + parts.join(", ") + " ]";
}

function motokoExpectedEntries(entries: readonly [number, string][]): string {
  if (entries.length === 0) {
    return "[]";
  }
  const parts = entries.map(
    ([k, v]) => `(${k}, ${motokoTextLiteral(v)})`,
  );
  return "[ " + parts.join(", ") + " ]";
}

/**
 * Replay commands like `fc.modelRun`, recording only mutating ops for Motoko.
 * `get` commands are executed but not included in the trace.
 */
function sampleMutationOps(maxCommands: number, seed: number): MapMutationOp[] {
  const samples = fc.sample(
    mapCommandArbitrary({ maxCommands }),
    { seed, numRuns: 1 },
  );
  const iterable = samples[0] as Iterable<
    fc.Command<MapModel, OracleNatTextMap>
  >;
  const model: MapModel = { map: new Map() };
  const real = new OracleNatTextMap();
  const ops: MapMutationOp[] = [];
  for (const cmd of iterable) {
    if (!cmd.check(model)) {
      continue;
    }
    const mut = commandToMapMutationOp(cmd);
    if (mut !== null) {
      ops.push(mut);
    }
    cmd.run(model, real);
  }
  return ops;
}

function buildModule(baseSeed: number): string {
  const fixtureLiterals: string[] = [];
  for (let i = 0; i < FIXTURE_COUNT; i++) {
    const maxCommands = maxCommandsForFixture(i);
    const seed = seedForFixture(i, baseSeed);
    const mutOps = sampleMutationOps(maxCommands, seed);
    const expected = applyMapMutationOps(mutOps);
    fixtureLiterals.push(
      `{ mutations = ${motokoMutationOpsArray(mutOps)}; expectedEntries = ${motokoExpectedEntries(expected)} }`,
    );
  }

  return `// Generated by test/ts/pbt/emitOracleFixtures.ts - do not edit by hand.
// Regenerate: npm run generate:oracle-fixtures
// Reproduce this file: ORACLE_FIXTURE_SEED=${baseSeed} npm run generate:oracle-fixtures

module {
  public type MutationOp = {
    #add : (Nat, Text);
    #remove : Nat;
  };

  public type Fixture = {
    mutations : [MutationOp];
    expectedEntries : [(Nat, Text)];
  };

  public let fixtureCount : Nat = ${FIXTURE_COUNT};

  public let fixtures : [Fixture] = [ ${fixtureLiterals.join(", ")} ];
};
`;
}

export function writeMapOracleFixtures(baseSeed: number): void {
  const outDir = join(__dirname, "../../generated");
  mkdirSync(outDir, { recursive: true });
  const outPath = join(outDir, "MapOracleFixtures.mo");
  writeFileSync(outPath, buildModule(baseSeed), "utf8");
  console.log(`Wrote ${outPath} (${FIXTURE_COUNT} fixtures, base seed ${baseSeed})`);
}
