name: publish on Mops

on:
  workflow_dispatch:
  push:
    tags:
      - preview-*
      - v*.*.*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dfinity/setup-dfx@e50c04f104ee4285ec010f10609483cf41e4d365 # main
      - uses: ZenVoich/setup-mops@3e94e453352269b34137b5ce49f09a8df81bed7d # v1.4.1
        with:
          # Make sure you set the MOPS_IDENTITY_PEM secret in your repository settings https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository
          identity-pem: ${{ secrets.MOPS_IDENTITY_PEM }}
      - run: mops install
      - run: mops publish
